### ISSUE TITLE
Stop sound on component unmount

### ISSUE THREAD

**Issue by kosijer** [kosijer/lanterns#42]
Once we merge #41 we will get the sound on About page
But the sound doesn't stop after we click away

I tried with useEffect cleanup callback but it didn't work

Maybe we should trigger it when URL location change, but I didn't know how Gatsby handles this. Maybe you'll have better idea

Anyway, I used this library
https://www.npmjs.com/package/use-sound

**Comment by rnaidenov** [comment]
Woooho fixed!
