### ISSUE TITLE
Add lantern hover

### ISSUE THREAD

**Issue by kosijer** [kosijer/lanterns#73]
![image](https://user-images.githubusercontent.com/10941060/108442900-c18a9600-724f-11eb-8f4c-0258f48e7da9.png)

**Comment by rnaidenov** [comment]
This will come in the next PR (:

**Comment by kosijer** [comment]
@rnaidenov 
Is that the one I merged this morning?

One tip...
You can easily link PR with the issue(s) by mentioning "fixes" (or "closes" or "resolves" or anything from this list https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) and then add issue number next to it. 

In this case it will be Closes #73

Then it will automatically close issue when we close/merge PR

**Comment by rnaidenov** [comment]
Thank you for the tip (: !
